services:
  lb:
    build: .
    image: "${WEBAPI_IMAGE:-rinha4-yolo-mode:local}"
    command: ["/app/lb"]
    platform: linux/amd64
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - sockets:/tmp/rinha
    networks:
      - rinha
    logging:
      driver: "none"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.06"
          memory: "30M"

  api1:
    build: .
    image: "${WEBAPI_IMAGE:-rinha4-yolo-mode:local}"
    command: ["/app/api", "/tmp/rinha/api1.sock"]
    platform: linux/amd64
    volumes:
      - sockets:/tmp/rinha
    networks:
      - rinha
    logging:
      driver: "none"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "160M"

  api2:
    build: .
    image: "${WEBAPI_IMAGE:-rinha4-yolo-mode:local}"
    command: ["/app/api", "/tmp/rinha/api2.sock"]
    platform: linux/amd64
    volumes:
      - sockets:/tmp/rinha
    networks:
      - rinha
    logging:
      driver: "none"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "160M"

networks:
  rinha:
    driver: bridge

volumes:
  sockets:
