services:
  lb:
    image: ronieneubauer/rinha2026@sha256:45d124de26f71d869d55a5805ddfefdd008811155ae3d8aa8380201355270d97
    restart: unless-stopped
    command: ["./lb"]
    environment:
      - PORT=9999
      - UPSTREAMS=/sockets/api1.sock,/sockets/api2.sock
      - RINHA_BACKEND_REPEATS=2
      - RINHA_BUSY_POLL_US=0
      - RINHA_HEALTH_PEEK_MS=5
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9999/ready"]
      interval: 2s
      timeout: 5s
      retries: 15
    deploy:
      resources:
        limits:
          cpus: "0.06"
          memory: "30M"

  api1:
    image: ronieneubauer/rinha2026@sha256:45d124de26f71d869d55a5805ddfefdd008811155ae3d8aa8380201355270d97
    restart: unless-stopped
    command: ["./server"]
    security_opt:
      - seccomp:unconfined
    environment:
      - UDS_PATH=/sockets/api1.sock
      - WORKERS=2
      - RINHA_CPU=0
      - RINHA_BUSY_POLL_US=0
      - RINHA_MAX_PROBES=20
      - RINHA_FAST_PROBES=5
      - RINHA_CLUSTER_SCORE=centroid
      - RINHA_FAST_ADAPTIVE_MIN=99
      - RINHA_FAST_ADAPTIVE_MAX=0
      - RINHA_FAST_T0=0
      - RINHA_FAST_T1=0
      - RINHA_FAST_T2=3876355
      - RINHA_FAST_T3=3144476
      - RINHA_FAST_T4=5217400
      - RINHA_FAST_T5=0
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      rtprio: 99
      memlock: -1
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "160M"

  api2:
    image: ronieneubauer/rinha2026@sha256:45d124de26f71d869d55a5805ddfefdd008811155ae3d8aa8380201355270d97
    restart: unless-stopped
    command: ["./server"]
    security_opt:
      - seccomp:unconfined
    environment:
      - UDS_PATH=/sockets/api2.sock
      - WORKERS=2
      - RINHA_CPU=2
      - RINHA_BUSY_POLL_US=0
      - RINHA_MAX_PROBES=20
      - RINHA_FAST_PROBES=5
      - RINHA_CLUSTER_SCORE=centroid
      - RINHA_FAST_ADAPTIVE_MIN=99
      - RINHA_FAST_ADAPTIVE_MAX=0
      - RINHA_FAST_T0=0
      - RINHA_FAST_T1=0
      - RINHA_FAST_T2=3876355
      - RINHA_FAST_T3=3144476
      - RINHA_FAST_T4=5217400
      - RINHA_FAST_T5=0
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      rtprio: 99
      memlock: -1
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "160M"

volumes:
  sockets: