services:
  api-0:
    image: ghcr.io/gabrielrauch/rinha-2026:latest
    platform: linux/amd64
    pull_policy: always
    environment:
      RINHA_THREADS: "1"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "165M"
    expose:
      - "8000"

  api-1:
    image: ghcr.io/gabrielrauch/rinha-2026:latest
    platform: linux/amd64
    pull_policy: always
    environment:
      RINHA_THREADS: "1"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "165M"
    expose:
      - "8000"

  lb:
    image: haproxy:2.9-alpine
    platform: linux/amd64
    pull_policy: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    depends_on:
      - api-0
      - api-1
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20M"

networks:
  rinha:
    driver: bridge
